version: '3'
services:

  pbg-ld:
    image: candygene/pbg-ld
    container_name: pbg-ld
    ports:
      - 8890:8890
      - 1111:1111

  fdp:
    image: nlesc/odex-fairdatapoint:candygene
    container_name: fdp
    depends_on:
      - pbg-ld
    ports:
      - 8080:8080

  grlc:
    image: clariah/grlc
    container_name: grlc
    depends_on:
      - pbg-ld
    ports:
      - 8088:8088
    environment:
      - DEBUG=true
      - GRLC_GITHUB_ACCESS_TOKEN=xxx
      - GRLC_SERVER_NAME=localhost:8088
      - GRLC_SPARQL_ENDPOINT=http://pbg-ld:8890/sparql
