version: '3'
services:

  ara-ld:
    image: candygene/ara-ld:latest
    container_name: ara-ld
    ports:
      - 8890:8890

  grlc:
    image: clariah/grlc:latest
    container_name: grlc
    depends_on:
      - ara-ld
    ports:
      - 8088:8088
    environment:
      - DEBUG=true
      - GRLC_GITHUB_ACCESS_TOKEN=xxx
      - GRLC_SERVER_NAME=localhost:8088
      - GRLC_SPARQL_ENDPOINT=http://ara-ld:8890/sparql  # dev
