version: '3'
services:

  ara-ld:
    image: candygene/ara-ld
    container_name: ara-ld
    ports:
      - 8890:8890

  grlc:
    image: clariah/grlc
    container_name: grlc
    depends_on:
      - ara-ld
    ports:
      - 8088:8088
    environment:
      - DEBUG=true
      - GRLC_GITHUB_ACCESS_TOKEN=25ffeec9135467e5bbb81ecda7a95eb2a56826a0
      - GRLC_SERVER_NAME=localhost:8088
      - GRLC_SPARQL_ENDPOINT=http://ara-ld:8890/sparql  # dev
