-- 
-- SPARQL query to cross-reference chromosomes in two RDF graphs.
--   graph URI: https://solgenomics.net/genome/Solanum_lycopersicum
--     chromosome URI: e.g. http://solgenomics.net/genome/Solanum_lycopersicum/chromosome/SL2.50ch01
--
--   graph URI: http://plants.ensembl.org/Solanum_lycopersicum
--     chromosome URI: e.g. http://rdf.ebi.ac.uk/resource/ensembl/32/solanum_lycopersicum/SL2.50/1
--
-- Prerequisite: GRANT SPARQL_UPDATE to "SPARQL";
--

PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

INSERT INTO <https://solgenomics.net/genome/Solanum_lycopersicum> {
   ?chr1 owl:sameAs ?chr2
}   
WHERE {
   GRAPH <https://solgenomics.net/genome/Solanum_lycopersicum> {
      ?chr1 a obo:SO_0000340 .
      BIND(uri(concat('http://rdf.ebi.ac.uk/resource/ensembl/32/solanum_lycopersicum/SL2.50/', replace(str(?chr1), '.+ch0?', ''))) AS ?chr2)
   }
}

--
-- SPARQL query to delete above triples
--
-- PREFIX owl: <http://www.w3.org/2002/07/owl#>
-- WITH  <https://solgenomics.net/genome/Solanum_lycopersicum>
-- DELETE WHERE
-- { ?s owl:sameAs ?o }

--
-- SPARQL query to link SGN tomato chromosomes to ENA accessions
--

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX sgn: <http://solgenomics.net/genome/Solanum_lycopersicum/chromosome/>
PREFIX ena: <http://identifiers.org/ena.embl/>

INSERT INTO <https://solgenomics.net/genome/Solanum_lycopersicum> {
   sgn:SL2.50ch01 rdfs:seeAlso ena:CM001064.2 .
   sgn:SL2.50ch02 rdfs:seeAlso ena:CM001065.2 .
   sgn:SL2.50ch03 rdfs:seeAlso ena:CM001066.2 .
   sgn:SL2.50ch04 rdfs:seeAlso ena:CM001067.2 .
   sgn:SL2.50ch05 rdfs:seeAlso ena:CM001068.2 .
   sgn:SL2.50ch06 rdfs:seeAlso ena:CM001069.2 .
   sgn:SL2.50ch07 rdfs:seeAlso ena:CM001070.2 .
   sgn:SL2.50ch08 rdfs:seeAlso ena:CM001071.2 .
   sgn:SL2.50ch09 rdfs:seeAlso ena:CM001072.2 .
   sgn:SL2.50ch10 rdfs:seeAlso ena:CM001073.2 .
   sgn:SL2.50ch11 rdfs:seeAlso ena:CM001074.2 .
   sgn:SL2.50ch12 rdfs:seeAlso ena:CM001075.2
}

