-- 
-- SPARQL query to add missing chromosome type (triples) to EnsEMBL RDF graph.
--
-- Prerequisite: GRANT SPARQL_UPDATE to "SPARQL";
--

PREFIX obo: <http://purl.obolibrary.org/obo/>

INSERT INTO <http://plants.ensembl.org/Solanum_lycopersicum> {
   ?chr2 a obo:SO_0000340
}  
WHERE {
   GRAPH <https://solgenomics.net/genome/Solanum_lycopersicum> {
      ?chr1 a obo:SO_0000340 .
      BIND(uri(concat('http://rdf.ebi.ac.uk/resource/ensembl/32/solanum_lycopersicum/SL2.50/', replace(str(?chr1), '.+ch0?', ''))) AS ?chr2)
   }
}

--
-- SPARQL query to delete above triples
--
-- PREFIX obo: <http://purl.obolibrary.org/obo/>
-- WITH  <http://plants.ensembl.org/Solanum_lycopersicum>
-- DELETE WHERE
-- { ?s a obo:SO_0000340 }
